---
title: "RAdelaide 2024"
author: |
  | Dr Stevie Pederson
  | Black Ochre Data Labs
  | Indigenous Genomics
  | Telethon Kids Institute
date: "July 9-11, 2024"
output: github_document
---

```{r, echo=FALSE}
getTiming <- function(f, by = 1, digits = -1){
  # by estimates how many minutes/slide
  ln <- readLines(here::here(f))
  n <- sum(grepl("^#{2} ", ln))
  paste0(round(n * by, digits), "min")
}
```

## Course Details

This will be a three day course to enable researchers to develop their capabilities using the language `R`.
Beginners are welcome and intermediate users will also gain a great deal from attending.

Data for the workshop is available as a zip file [here](data.zip)

## Provisional Course Outline

| Day 1 | Topic | Notes | Estimated Duration <br>(approx) |
|:----- |:----- |:----- |:-------- |
| 9:00  | Welcome To Country |     | 15min    |
|   | Installation Help  |     | 15min    |
|  | Introducing R & RStudio | [Introduction](intro.html) | `r getTiming("intro_slides.qmd", 0.9)`|
|  | Spreadsheet-Like Data   | [Data Import](import.html) | `r getTiming("import_slides.qmd", 1.2)`|
| 10:30 | *Morning Tea* | | |
| 11:00 | Spreadsheet-Like Data (continued) | | |
| | Exploring & Manipulating Data | [Data Exploration](exploring.html) | `r getTiming("exploring_slides.qmd", 1)` |
| 12:30 | *Lunch* | | |
| 1:30  | Visualising Your Data with `ggplot2` | [Introductory Visualisation](intro_vis.html) | `r getTiming("intro_vis_slides.qmd", 1.5)` |
|  | Using `stringr` to Modify Text | [Working With Text](text.html) | `r getTiming("text_slides.qmd")` |
| 3:00  | *Afternoon Tea* | | |
| 3:30  | Reshaping Data With `tidyr` | [Reshaping Data](tidyr.html) | `r getTiming("tidyr_slides.qmd")` |
| 4:00 | Challenges and Bring Your Own Data  | [Day1](day1.html) | |


| Day 2 | Topic | Notes | Estimated Duration <br>(approx) |
|:----- |:----- |:----- |:-------- |
| 9:00 | Day 1 Challenges | [Day1](day1.html) | 30min|
| 9:30 | Using `stringr` to Modify Text (continued) | [Working With Text](text.html) | 15min |
| 9:45 | Reshaping Data With `tidyr` | [Reshaping Data](tidyr.html) | `r getTiming("tidyr_slides.qmd")` |
| 10:05 | Using Rmarkdown | [RMarkdown](rmarkdown.html) | `r getTiming("rmarkdown_slides.qmd", 1.5)` |
| 10:30 | *Morning Tea* | | |
| 11:00 | Using Rmarkdown (continued) | | |
| 11:30  | Vectors and Data Structures in `R` | [Data Types](data_types.html) | `r getTiming("data_types_slides.qmd", 1.2)` |
| 12:30 | *Lunch* | | |
| 1:30 | Basic Statistical Analysis | [Basic Statistics](basic_stats.html) | `r getTiming("basic_stats_slides.qmd", 1.5)` |
| 3:00  | *Afternoon Tea* | | |
| 3:30  | Functions | [Functions](functions.html) | `r getTiming("functions_slides.qmd", 1.2)` |




| Day 3 | Topic | Notes | Estimated Duration <br>(approx) |
|:----- |:----- |:----- |:-------- |
| 9:00  | The Bioconductor Project | [The Bioconductor Project](intro_bioc.html) | `r getTiming("intro_bioc_slides.qmd")` |
| | Working with Sequences and Genomic Ranges | [References and Ranges](references.html) | `r getTiming("references_slides.qmd")` |
| 10:30 | *Morning Tea* | | |
| 11:00 | Introduction to RNA-Seq | [RNA-Seq](rna_seq.html) |  `r getTiming("rna_seq_slides.qmd", 1.2)` |
|  | Bulk RNA-Seq Analysis | [Differential Gene Expression](deg.html) | `r getTiming("deg_slides.qmd", 1.5)` |
| 12:30 | *Lunch* | | |
| 1:30 | Bulk RNA-Seq Analysis (continued) | |  |
| | Enrichment Analysis | [Finding the Underlying Biology](enrichment.html) | `r getTiming("enrichment_slides.qmd", 1.5)` |
| 3:00  | *Afternoon Tea* | | |
| 3:30 | Enrichment Analysis (continued) | | |
| 4:00  | Challenges & Bring Your Own Data | | |
